language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build --no-cache -t cloudqq/alpine-node-v5.12.0 .
  - docker tag cloudqq/alpine-node-v5.12.0:latest cloudqq/alpine-node-v5.12.0:v1
  - docker push cloudqq/alpine-node-v5.12.0